import { Employee } from './employee.model';

// Mock hierarchy data lives in a separate file so HTML and services do not hardcode data.
// Later this same shape can come from an ASP.NET Core API response.
export const ORGANIZATION_MENU_MOCK: Employee[] =  [
  
  {
    EmpNo: '100003',
    EmployeeName: 'PROBHAS BONDHU CHAKRABORTY',
    DesignationName: 'MANAGING DIRECTOR(MD)',
    ManagerNo: null,
    ManagerName: null,
    ImageUrl: null,
  },
  {
    EmpNo: '100471',
    EmployeeName: 'SUROJIT SEN',
    DesignationName: 'MANAGER- SYSTEM & IT(HOD)',
    ManagerNo: '100003',
    ManagerName: 'PROBHAS BONDHU CHAKRABORTY',
    ImageUrl: null,
  },
  {
    EmpNo: '100635',
    EmployeeName: 'SOUMITRA MANDAL',
    DesignationName: 'SYSTEM ASSISTANT',
    ManagerNo: '100471',
    ManagerName: 'SUROJIT SEN',
    ImageUrl: null,
  },
  {
    EmpNo: '100894',
    EmployeeName: 'RAHUL TRIPATHY',
    DesignationName: 'DEPUTY ZONAL SALES MANAGER',
    ManagerNo: '100471',
    ManagerName: 'SUROJIT SEN',
    ImageUrl: null,
  },
  {
    EmpNo: '101010',
    EmployeeName: 'MAYUKH CHOWDHURY',
    DesignationName: 'SENIOR WEB DEVELOPER',
    ManagerNo: '100471',
    ManagerName: 'SUROJIT SEN',
    ImageUrl: null,
  },
  {
    EmpNo: '101011',
    EmployeeName: 'RIMPA DAS MALLICK',
    DesignationName: 'SYSTEM ANALYST',
    ManagerNo: '100471',
    ManagerName: 'SUROJIT SEN',
    ImageUrl: null,
  },
  {
    EmpNo: '101014',
    EmployeeName: 'PALLAB DAS',
    DesignationName: 'SENIOR WEB DEVELOPER',
    ManagerNo: '100471',
    ManagerName: 'SUROJIT SEN',
    ImageUrl: null,
  },
  {
    EmpNo: '101328',
    EmployeeName: 'SRAMANA BHADURI',
    DesignationName: 'QA_MIS',
    ManagerNo: '100471',
    ManagerName: 'SUROJIT SEN',
    ImageUrl: null,
  },
  {
    EmpNo: '101450',
    EmployeeName: 'SUVAJIT DAS',
    DesignationName: 'SENIOR WEB DEVELOPER',
    ManagerNo: '100471',
    ManagerName: 'SUROJIT SEN',
    ImageUrl: null,
  },
  {
    EmpNo: '101507',
    EmployeeName: 'SAIKAT SARKAR',
    DesignationName: 'SENIOR WEB DEVELOPER',
    ManagerNo: '100471',
    ManagerName: 'SUROJIT SEN',
    ImageUrl: null,
  },
  {
    EmpNo: '101532',
    EmployeeName: 'UDIT CHAKRABORTY',
    DesignationName: 'BUSINESS DEVELOPMENT MANAGER',
    ManagerNo: '100471',
    ManagerName: 'SUROJIT SEN',
    ImageUrl: null,
  },
  {
    EmpNo: '101723',
    EmployeeName: 'ANINDITA BANERJEE',
    DesignationName: 'MARKET RESEARCH EXECUTIVE',
    ManagerNo: '101532',
    ManagerName: 'UDIT CHAKRABORTY',
    ImageUrl: null,
  },
  {
    EmpNo: '100601',
    EmployeeName: 'PRADIP DAS',
    DesignationName: 'OFFICER',
    ManagerNo: '101507',
    ManagerName: 'SAIKAT SARKAR',
    ImageUrl: null,
  },
  {
    EmpNo: '100773',
    EmployeeName: 'BIPRADAS GUIN',
    DesignationName: 'SENIOR OFFICER',
    ManagerNo: '101507',
    ManagerName: 'SAIKAT SARKAR',
    ImageUrl: null,
  },
  {
    EmpNo: '101511',
    EmployeeName: 'PIJUSH MONDAL',
    DesignationName: 'MANAGEMENT TRAINEE',
    ManagerNo: '101507',
    ManagerName: 'SAIKAT SARKAR',
    ImageUrl: null,
  },
  {
    EmpNo: '101632',
    EmployeeName: 'SHREYA MANNA',
    DesignationName: 'MANAGEMENT TRAINEE',
    ManagerNo: '101507',
    ManagerName: 'SAIKAT SARKAR',
    ImageUrl: null,
  },
  {
    EmpNo: '101069',
    EmployeeName: 'MEGA DHAR',
    DesignationName: 'WEB DEVELOPER',
    ManagerNo: '101450',
    ManagerName: 'SUVAJIT DAS',
    ImageUrl: null,
  },
  {
    EmpNo: '101255',
    EmployeeName: 'ANUJ KUMAR MAHLI',
    DesignationName: 'APP DEVELOPER',
    ManagerNo: '101450',
    ManagerName: 'SUVAJIT DAS',
    ImageUrl: null,
  },
  {
    EmpNo: '101343',
    EmployeeName: 'SAIKAT MONDAL',
    DesignationName: 'JUNIOR WEB DEVELOPER',
    ManagerNo: '101450',
    ManagerName: 'SUVAJIT DAS',
    ImageUrl: null,
  },
  {
    EmpNo: '101536',
    EmployeeName: 'CHANDAN MISHRA',
    DesignationName: 'MANAGEMENT TRAINEE',
    ManagerNo: '101450',
    ManagerName: 'SUVAJIT DAS',
    ImageUrl: null,
  },
  {
    EmpNo: '101512',
    EmployeeName: 'SRIJONI CHAKRABORTY',
    DesignationName: 'MANAGEMENT TRAINEE',
    ManagerNo: '101328',
    ManagerName: 'SRAMANA BHADURI',
    ImageUrl: null,
  },
  {
    EmpNo: '101044',
    EmployeeName: 'SAIKAT MAITY',
    DesignationName: 'ANDROID DEVELOPER',
    ManagerNo: '101010',
    ManagerName: 'MAYUKH CHOWDHURY',
    ImageUrl: null,
  },
  {
    EmpNo: '101337',
    EmployeeName: 'SOUVIK DHAR',
    DesignationName: 'JUNIOR WEB DEVELOPER',
    ManagerNo: '101010',
    ManagerName: 'MAYUKH CHOWDHURY',
    ImageUrl: null,
  },
  {
    EmpNo: '101395',
    EmployeeName: 'SWARNALI RAHA',
    DesignationName: 'SYSTEM ANALYST',
    ManagerNo: '101010',
    ManagerName: 'MAYUKH CHOWDHURY',
    ImageUrl: null,
  },
  {
    EmpNo: '101636',
    EmployeeName: 'SOHAM DEY',
    DesignationName: 'MANAGEMENT TRAINEE',
    ManagerNo: '101010',
    ManagerName: 'MAYUKH CHOWDHURY',
    ImageUrl: null,
  },
  {
    EmpNo: '101020',
    EmployeeName: 'ASIT DAS',
    DesignationName: 'OFFICER',
    ManagerNo: '100635',
    ManagerName: 'SOUMITRA MANDAL',
    ImageUrl: null,
  },
  {
    EmpNo: '101719',
    EmployeeName: 'BIPLAB MAJUMDER',
    DesignationName: 'OFFICER',
    ManagerNo: '100635',
    ManagerName: 'SOUMITRA MANDAL',
    ImageUrl: null,
  },
  {
    EmpNo: '101403',
    EmployeeName: 'SUMAN JANA',
    DesignationName: 'APP DEVELOPER',
    ManagerNo: '101044',
    ManagerName: 'SAIKAT MAITY',
    ImageUrl: null,
  },
  {
    EmpNo: '101500',
    EmployeeName: 'BISWARUP DUTTA',
    DesignationName: 'MANAGEMENT TRAINEE',
    ManagerNo: '101255',
    ManagerName: 'ANUJ KUMAR MAHLI',
    ImageUrl: null,
  },
  {
    EmpNo: '100888',
    EmployeeName: 'BIPRO DAS',
    DesignationName: 'OFFICER',
    ManagerNo: '100773',
    ManagerName: 'BIPRADAS GUIN',
    ImageUrl: null,
  },
  {
    EmpNo: '101597',
    EmployeeName: 'SUBHAJIT KAJLI',
    DesignationName: 'TRAINEE',
    ManagerNo: '100773',
    ManagerName: 'BIPRADAS GUIN',
    ImageUrl: null,
  }
];
